# Generated by Django 5.2.1 on 2025-05-28 06:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_article_articleimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
        migrations.AlterModelOptions(
            name='articleimage',
            options={},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='author',
            new_name='creator',
        ),
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='articleimage',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='articleimage',
            name='order',
        ),
        migrations.AddField(
            model_name='articleimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/'),
        ),
    ]
