# Generated by Django 5.2.1 on 2025-05-30 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_studentanswer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, help_text='Краткое описание статьи', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='total_pages',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('page_number', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/pages/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='api.article')),
            ],
            options={
                'ordering': ['page_number'],
                'unique_together': {('article', 'page_number')},
            },
        ),
        migrations.CreateModel(
            name='ArticleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_page', models.IntegerField(default=1)),
                ('last_read_at', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='api.article')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'article')},
            },
        ),
        migrations.DeleteModel(
            name='ArticleImage',
        ),
    ]
