# Generated by Django 5.2.1 on 2025-05-31 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='position',
            field=models.CharField(choices=[('WAITER', 'Официант'), ('BARTENDER', 'Бармен'), ('MANAGER', 'Менеджер'), ('CLEANER', 'Уборщик'), ('COOK', 'Повар')], default='WAITER', max_length=20, verbose_name='Должность'),
        ),
    ]
