# Generated by Django 5.2.1 on 2025-05-31 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_student_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='positions',
            field=models.ManyToManyField(blank=True, related_name='articles', to='api.position'),
        ),
        migrations.AddField(
            model_name='course',
            name='positions',
            field=models.ManyToManyField(blank=True, related_name='courses', to='api.position'),
        ),
        migrations.AddField(
            model_name='test',
            name='positions',
            field=models.ManyToManyField(blank=True, related_name='tests', to='api.position'),
        ),
    ]
